export const PERMISSIONS = [
  ['platform.tenants', 'Platform', 'View and manage every tenant'],
  ['platform.health', 'Platform', 'View system health and usage'],
  ['settings.manage', 'Organization', 'Edit branding, subscription, and configuration'],
  ['clinics.manage', 'Clinics', 'Create and edit branches and facilities'],
  ['clinics.all', 'Clinics', 'Work across every branch'],
  ['users.manage', 'People', 'Manage staff accounts and roles'],
  ['patients.read', 'Patients', 'View patient records'],
  ['patients.write', 'Patients', 'Register and update patients'],
  ['appointments.read', 'Appointments', 'View the schedule'],
  ['appointments.write', 'Appointments', 'Book and update appointments'],
  ['emr.read', 'EMR', 'View clinical notes'],
  ['emr.write', 'EMR', 'Write clinical notes and vitals'],
  ['prescriptions.read', 'Pharmacy', 'View prescriptions'],
  ['prescriptions.write', 'Pharmacy', 'Write prescriptions'],
  ['lab.read', 'Laboratory', 'View lab orders and results'],
  ['lab.write', 'Laboratory', 'Order tests and enter results'],
  ['imaging.read', 'Imaging', 'View imaging orders'],
  ['imaging.write', 'Imaging', 'Create studies and reports'],
  ['pharmacy.read', 'Pharmacy', 'View the medicine catalog and stock'],
  ['pharmacy.write', 'Pharmacy', 'Dispense and update stock'],
  ['billing.read', 'Finance', 'View invoices and payments'],
  ['billing.write', 'Finance', 'Create invoices and take payments'],
  ['insurance.read', 'Insurance', 'View policies and claims'],
  ['insurance.write', 'Insurance', 'Manage insurers and claims'],
  ['inventory.read', 'Inventory', 'View stock, suppliers, and purchase orders'],
  ['inventory.write', 'Inventory', 'Adjust stock and receive goods'],
  ['hr.read', 'People', 'View attendance, shifts, and leave'],
  ['hr.write', 'People', 'Record attendance and leave'],
  ['reports.read', 'Reports', 'View operational dashboards'],
  ['audit.read', 'Security', 'View activity and login history'],
  ['notifications.read', 'Notifications', 'View notifications'],
  ['telemed.join', 'Telemedicine', 'Join a video consult'],
  ['ai.use', 'AI', 'Use chart briefs and operational forecasts'],
  ['portal.access', 'Portal', 'Use the patient portal']
];

const clinical = [
  'patients.read', 'patients.write', 'appointments.read', 'appointments.write',
  'emr.read', 'emr.write', 'prescriptions.read', 'prescriptions.write',
  'lab.read', 'imaging.read', 'imaging.write', 'telemed.join', 'ai.use',
  'reports.read', 'notifications.read'
];

export const ROLE_GRANTS = {
  super_admin: PERMISSIONS.map(([key]) => key),
  org_admin: PERMISSIONS.map(([key]) => key).filter((key) => !key.startsWith('platform.')),
  clinic_admin: PERMISSIONS.map(([key]) => key).filter((key) => !key.startsWith('platform.') && key !== 'settings.manage'),
  doctor: clinical,
  nurse: ['patients.read', 'patients.write', 'appointments.read', 'appointments.write', 'emr.read', 'emr.write', 'lab.read', 'imaging.read', 'notifications.read'],
  receptionist: ['patients.read', 'patients.write', 'appointments.read', 'appointments.write', 'billing.read', 'notifications.read'],
  pharmacist: ['patients.read', 'prescriptions.read', 'pharmacy.read', 'pharmacy.write', 'inventory.read', 'inventory.write', 'billing.read', 'billing.write', 'notifications.read'],
  lab_technician: ['patients.read', 'lab.read', 'lab.write', 'notifications.read'],
  accountant: ['billing.read', 'billing.write', 'insurance.read', 'insurance.write', 'reports.read', 'notifications.read'],
  hr_admin: ['hr.read', 'hr.write', 'users.manage', 'reports.read', 'notifications.read'],
  patient: ['portal.access', 'appointments.read', 'appointments.write', 'emr.read', 'prescriptions.read', 'lab.read', 'imaging.read', 'billing.read', 'telemed.join', 'notifications.read']
};

export const ROLE_NAMES = {
  super_admin: 'Super Admin',
  org_admin: 'Organization Admin',
  clinic_admin: 'Clinic Admin',
  doctor: 'Doctor',
  nurse: 'Nurse',
  receptionist: 'Receptionist',
  pharmacist: 'Pharmacist',
  lab_technician: 'Lab Technician',
  accountant: 'Accountant',
  hr_admin: 'HR Admin',
  patient: 'Patient'
};

export const BACKUP_TABLES = [
  'roles',
  'role_permissions',
  'clinics',
  'users',
  'user_clinics',
  'departments',
  'user_departments',
  'rooms',
  'wards',
  'beds',
  'services',
  'service_prices',
  'working_hours',
  'holidays',
  'staff_profiles',
  'doctor_schedules',
  'doctor_leaves',
  'mrn_counters',
  'patients',
  'emergency_contacts',
  'allergies',
  'conditions',
  'surgeries',
  'family_histories',
  'patient_documents',
  'consents',
  'shifts',
  'attendance',
  'leave_requests',
  'appointments',
  'waiting_list',
  'encounters',
  'vitals',
  'referrals',
  'medical_certificates',
  'medicines',
  'suppliers',
  'prescriptions',
  'prescription_items',
  'stock_batches',
  'stock_movements',
  'purchase_orders',
  'purchase_order_items',
  'lab_tests',
  'lab_orders',
  'lab_order_items',
  'imaging_orders',
  'insurers',
  'insurance_plans',
  'invoices',
  'invoice_lines',
  'payments',
  'patient_policies',
  'claims',
  'notifications',
  'consult_messages',
  'integrations',
  'webhooks'
];
